language: cpp
compiler:
  - gcc
script: 
  - g++ Original\ Minimax/minimax.cpp -o minimax
  - g++ Alpha-Beta\ Pruning/minimax_prun.cpp -o minimax_prun
  - ./minimax travis-ci_test.txt
  - ./minimax travis-ci_test.txt
  - ./minimax_prun travis-ci_test.txt
  - ./minimax_prun travis-ci_test.txt
